name: bynry_dbt
version: '0.1'
profile: bynry_dbt
config-version: 2
model-paths:
  - models
analysis-paths:
  - analysis
test-paths:
  - tests
seed-paths:
  - data
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_modules
  - logs
models:
  bynry_dbt:
    materialized: view