name: bynry_dbt
version: 1.0.0
config-version: 2
profile: bynry_dbt
model-paths:
  - models
analysis-paths:
  - analyses
test-paths:
  - tests
seed-paths:
  - seeds
macro-paths:
  - macros
snapshot-paths:
  - snapshots
clean-targets:
  - target
  - dbt_packages
models:
  bynry_dbt:
    example:
      +materialized: table
target-path: target
